# Generated by Django 4.2.7 on 2023-11-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.BigIntegerField()),
                ('mjeku', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('price', models.IntegerField()),
                ('services', models.TextField()),
            ],
        ),
    ]
