# Generated by Django 4.2.7 on 2024-01-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=191, null=True)),
                ('nr_cel', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=191, null=True)),
                ('mjeku', models.CharField(max_length=191, null=True)),
                ('cmimi', models.CharField(max_length=50, null=True)),
                ('sherbimet', models.TextField(null=True)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
